gh=float(input("Ganho por hora: "))
h=int(input("Horas trabalhadas: "))
sb=(gh*h)
ir=(11/100*sb)
inss=(8/100*sb)
sind=(5/100*sb)
desc=(ir+inss+sind)
sl=(sb-desc)
print(f"Salário bruto: {sb: .2f} reais.")
print(f"Imposto de renda: {ir: .2f} reais.")
print(f"INSS: {inss: .2f} reais.")
print(f"Sindicato: {sind: .2f} reais.")
print(f"Salário líquido: {sl: .2f} reais.")
